release fixes
Need to add a revision number, otherwise libtool will tell us that revision
must not be a negative number, like:

error: REVISION '' must be a nonnegative integer

Also fix a typo on NEWS file.